users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9O/c0/WR9/t41B5MUjP/p2nSjPgkFiF8RlUQF5H9x+ZyJHSlPwaYa99Dy0wV8jm9l2eisV8bHezj9Tyd906P9DQWABoLpZbBm/FR7ZWggc+RkeBkS71Kt/lld0rUo4USmXo6dPnFVP3gaA8HO2D7P5Zk2SKSCcEUphBmPf8jD3G1H3XE2e5v4r2tx7V3I27Fto1tmSHvjQHQ/8+rix4fJMi65q+of+JmxJ6TubnW4j3umV4zPqDgJsxKV/jZBNWoAWpTchGLZ8E4MHKxt4pwudpJmZ5SaGazA9ZSwsjmVn+Z8YMRDLArzaDVzgFhCTxeAsO/PNFfetqOxU7TOG6arvm0b5BJ9DrwYdu7t9+UF06E84+/QxCJjRcXjCgaXiTXZ2JvhuipsPw9pwJA/pxTuKBgkFlkVBKXaCzb51h0BR21ivOW4d3ceaBZBpPbNhVkQAyqz/mS9Iv0NxTYta9MCD7fbYgizI/12U7K1Sl2nKKnSFEIBi7+sTT2RbTUuNJU= vmuser
